Chia-Network/cadt

src/utils/xls.js
=> fix: project inserted without orgUid duplicated in warehouse projects list

src/datalayer/persistance.js, src/tasks/sync-audit-table.js, src/tasks/sync-datalayer.js, src/tasks/sync-default-organizations.js, src/tasks/sync-governance-body.js, src/tasks/sync-organization-meta.js, src/tasks/sync-picklists.js
=> feat: check for datalayer and wallet conditions before

package-lock.json, package.json, src/config/config.cjs, src/config/logger.cjs, src/controllers/project.controller.js, src/database/index.js, src/datalayer/persistance.js, src/datalayer/syncService.js, src/datalayer/writeService.js, src/models/governance/governance.model.js, src/models/organizations/organizations.model.js, src/routes/index.js, src/server.js, src/tasks/sync-audit-table.js, src/tasks/sync-datalayer.js, src/tasks/sync-default-organizations.js, src/tasks/sync-governance-body.js, src/tasks/sync-organization-meta.js, src/tasks/sync-picklists.js, src/utils/config-loader.js, src/utils/csv-utils.js, src/utils/data-loaders.js, src/utils/xls.js, src/websocket.js
- Adding winston as a logging package
- Removing `Debug`
=> feat: add winston as a sole logging package

src/controllers/organization.controller.js, tests/resources/organization.spec.js
Fix/510 delete stage when deleting imported orgs
=> Fix: delete stage when deleting imported orgs

src/routes/index.js, src/utils/file-loader.js
Adding request header x-api-version to have package.json version
=> feat: adding request header x-api-version to have package.json version

src/middleware.js, src/routes/index.js
- set added header keys to allow using express `cors`
- set NEW x-datamodel header key
- refactor middleware
=> refactor: refactor application middleware

src/controllers/project.controller.js, src/controllers/units.controller.js
Fix: projects and units pagination issue
=> Fix: projects pagination issue

src/middleware.js
=> feat: add is-governance-body header key

src/middleware.js
=> fix: no cache for any API endpoint

src/config/logger.cjs
add package version to logger format
=> feat: add package version to logger format

src/controllers/staging.controller.js, src/database/migrations/20220708210357-adding-author-column-to-audit-table.js, src/database/migrations/index.js, src/models/audit/audit.modeltypes.cjs, src/models/projects/projects.model.js, src/models/staging/staging.model.js, src/models/units/units.model.js, src/tasks/sync-audit-table.js, src/validations/staging.validations.js
Feat: add author field to audit transactions
=> Feat: add author field to audit

src/datalayer/wallet.js, src/models/organizations/organizations.model.js
Adding wallet balance to organizations reponse
=> Feat: wallet balance to org

src/controllers/project.controller.js, src/database/migrations/20220721212845-add-optional-methodology2-field-to-project.js, src/database/migrations/index.js, src/datalayer/writeService.js, src/models/projects/projects.model.js, src/models/projects/projects.modeltypes.cjs, src/validations/projects.validations.js, tests/resources/projects.spec.js, tests/test-data/new-project.json, tests/test-data/update-project.json, tests/test-fixtures/project-fixtures.js, tests/test-fixtures/staging-fixtures.js
Added methodology2 field to Projects table
=> Feat: add optional methodology2 field to project

src/tasks/sync-audit-table.js
Fixes the author field value saved incorrectly in the audit column
=> Feat: fix author field

src/controllers/governance.controller.js, src/routes/v1/resources/governance.js
=> feat: add glossary to governance

docs/postman/Organization API.postman_collection.json, src/controllers/organization.controller.js, src/datalayer/writeService.js, src/models/organizations/organizations.model.js, src/routes/v1/resources/organization.js, src/validations/organizations.validations.js
=> feat: add mirror endpoint

src/controllers/project.controller.js, src/database/migrations/20220825124702-add-isTransfer-column.js, src/database/migrations/index.js, src/datalayer/syncService.js, src/models/staging/staging.modeltypes.cjs, src/routes/v1/resources/projects.js
Reverts Chia-Network/climate-warehouse#708
=> Revert "Revert "feat: add transfer project endpoint""

src/models/file-store/file-store.model.js
Fixes an error thrown by datalayer when trying to delete files
=> fix: filestore delete throwing error

src/config/config.js, src/config/logger.cjs, src/datalayer/fullNode.js, src/datalayer/persistance.js, src/datalayer/wallet.js, src/utils/chia-root.js, src/utils/config-loader.js
* Updates the chia cert loading to look for CHIA_ROOT
* Updates the hardcoded `~/.chia/climate-warehouse` paths to also be relative to chia root. 
* This has the effect of making the default climate-warehouse folder change to `~/.chia/mainnet/climate-warehouse` instead of just ``~/.chia/mainnet/climate-warehouse`
=> respect CHIA_ROOT if set

.github/workflows/build.yaml, build-scripts/deb/control.j2, package.json
Build linux arm binaries and .debs for x64 and arm64
=> Build .deb for linux

CHANGELOG.md, README.md
Only updating the README, so don't think I need to do the version bump...?
=> Updated README with installation docs

README.md
Improve readability of README for the systemd portion
=> More systemd readme2

.github/workflows/auto-release.yml, .github/workflows/build.yaml
Very minor change to make workflow more clear with additional names.
=> Add names to steps to make it more clear in workflow

.github/workflows/auto-release.yml, .github/workflows/build.yaml, build-scripts/deb/control.j2, package.json
Cleanup and bugfixes in the CI
=> Release: version 1.3.2

src/controllers/organization.controller.js
=> Revert "feat: remove meta_ prefix from metadata keys"

src/controllers/organization.controller.js
=> Revert "Revert "feat: remove meta_ prefix from metadata keys""

README.md
=> Grammar and typos README.md update

docs/cadt_rpc_api.md, package-lock.json, package.json, src/controllers/organization.controller.js, src/datalayer/persistance.js, src/datalayer/writeService.js, src/tasks/sync-registries.js, src/utils/data-assertions.js, tests/integration/project.spec.js
Reverts Chia-Network/cadt#1066
=> Revert "Release 1.7.15"

src/controllers/offer.controller.js
minor tweaks to offer functionality 
correction of (GET) /offer/accept to return a message stating that there is no imported offer to accept in such a case, instead of returning a 400 and error message
correction of /offer/cancel bug in which the resource never returned a response
=> feat: offer bug fix and RESTful compliance

src/controllers/offer.controller.js, src/controllers/organization.controller.js
feat: /offer/accept conforms to RESTful protocol. will return 200 with message if no offer
needs to be merged with https://github.com/Chia-Network/cadt-ui/pull/1310
=> /offer/accept conforms to RESTful protocol
